name: Validate capability probe outputs (python-jsonschema)

on:
  push:
    paths:
      - "tools/ppt_capability_probe.py"
      - "schemas/capability_probe.v1.1.1.schema.json"
  pull_request:

jobs:
  validate-probe-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install python-pptx jsonschema jq

      - name: Run probe (JSON)
        run: |
          # Use a repository sample or generated PPTX; adjust path accordingly
          python tools/ppt_capability_probe.py --file samples/sample.pptx --json > probe.json
          cat probe.json | jq '.metadata.tool_version, .status'

      - name: Validate JSON against schema
        run: |
          python - <<'PY'
          import json, sys
          from jsonschema import Draft202012Validator
          schema = json.load(open("schemas/capability_probe.v1.1.1.schema.json"))
          payload = json.load(open("probe.json"))
          validator = Draft202012Validator(schema)
          errors = sorted(validator.iter_errors(payload), key=lambda e: e.path)
          if errors:
              for e in errors:
                  print("Validation error:", e.message, "at", list(e.path))
              sys.exit(1)
          print("Validation OK")
          PY
